{
 "title": "Nebius Shared Filesystem (Extended)",
 "description": "Nebius Shared Filesystems Extended Overview.",
 "tags": [
  "Nebius",
  "Filesystem"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "filesystem",
    "label": "Filesystem",
    "query": {
     "query": "label_values({filesystem!~\".*_s[0-9]+\"},filesystem)"
    }
   },
   { "name": "client", "label": "Virtual Machines", "query": { "query": "label_values(client)" } }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "TotalBytesCount{component=\"storage_fs\", filesystem=\"${filesystem}\"}",
     "legendFormat": "TotalBytesCount"
    }
   ]
  },
  {
   "title": "Clients Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(MaxRequestBytes{filesystem=\"${filesystem}\",  component=\"client_fs\", request=\"ReadData\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 6, "w": 17, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_set(\n    MaxRequestBytes{filesystem=\"${filesystem}\",  component=\"client_fs\", request=\"ReadData\"},\n    \"name\", \"MaxRead\"\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_set(\n    MaxRequestBytes{filesystem=\"${filesystem}\",  component=\"client_fs\", request=\"WriteData\"},\n    \"name\", \"MaxWrite\"\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bytes used",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "AggregateUsedBytesCount{ component=\"storage_fs\", filesystem=\"${filesystem}\"}",
     "legendFormat": "UsedBytesCount"
    },
    {
     "expr": "TotalBytesCount{ component=\"storage_fs\", filesystem=\"${filesystem}\"}",
     "legendFormat": "TotalBytesCount"
    }
   ]
  },
  { "title": "Client", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "UsedBandwidth (Average)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sort_by_label(sum (rate(RequestBytes{filesystem=\"${filesystem}\",  component=\"client_fs\",instance=~\"$client\"})) by (request, client), \"request\")",
     "legendFormat": "{{client}}, {{request}}"
    }
   ]
  },
  {
   "title": "UsedBandwidth (Burst)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sort_by_label(sum (MaxRequestBytes{filesystem=\"${filesystem}\",  component=\"client_fs\",instance=~\"$client\"}) by (request, client), \"request\")",
     "legendFormat": "{{client}}, {{request}}"
    }
   ]
  },
  {
   "title": "UsedIOPS (Average)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sort_desc(sum (rate(Count{filesystem=\"${filesystem}\",  component=\"client_fs\",instance=~\"$client\"})) by (request))",
     "legendFormat": "{{request}}"
    }
   ]
  },
  {
   "title": "UsedIOPS (Burst)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sort_by_label(sum (MaxCount{filesystem=\"${filesystem}\",  component=\"client_fs\",instance=~\"$client\"}) by (request, client), \"request\")",
     "legendFormat": "{{client}}, {{request}}"
    }
   ]
  },
  {
   "title": "InProgressBytes (Average)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sort_by_label(sum (InProgressBytes{filesystem=\"${filesystem}\",  component=\"client_fs\",instance=~\"$client\"}) by (request, client), \"request\")",
     "legendFormat": "{{client}}, {{request}}"
    }
   ]
  },
  {
   "title": "InProgressBytes (Burst)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sort_by_label(sum (MaxInProgressBytes{filesystem=\"${filesystem}\",  component=\"client_fs\",instance=~\"$client\"}) by (request, client), \"request\")",
     "legendFormat": "{{client}}, {{request}}"
    }
   ]
  },
  {
   "title": "InProgressRequests (Average)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sort_desc(sum (InProgress{filesystem=\"${filesystem}\",  component=\"client_fs\",instance=~\"$client\"}) by (request))",
     "legendFormat": "{{request}}"
    }
   ]
  },
  {
   "title": "InProgressRequests (Burst)",
   "type": "timeseries",
   "description": "Note: burst metrics are not additive and may show times higher values than real values",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sort_desc(sum (MaxInProgress{filesystem=\"${filesystem}\",  component=\"client_fs\",instance=~\"$client\"}) by (request))",
     "legendFormat": "{{request}}"
    }
   ]
  },
  {
   "title": "WriteData Latency Quantiles (ms)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantiles(\"q\", 0.5, 0.9, 0.95, 0.99,\n  sum by (le) (\n    increase(Time_bucket{\n      filesystem=\"${filesystem}\",\n      component=\"client_fs\",\n      histogram=\"Time\",\n      request=\"WriteData\",\n      units=\"\",\n      instance=~\"$client\",\n    })\n  )\n) or \nhistogram_quantiles(\"q\", 0.5, 0.9, 0.95, 0.99,\n  sum by (le) (\n    increase(Time_bucket{\n      filesystem=\"${filesystem}\",\n      component=\"client_fs\",\n      histogram=\"Time\",\n      request=\"WriteData\",\n      units=\"usec\",\n      instance=~\"$client\",\n    })\n  )\n) / 1000",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "WriteData Execution Latency Quantiles (ms)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantiles(\"q\", 0.5, 0.9, 0.95, 0.99,\n  sum by (le) (\n    increase(ExecutionTime_bucket{\n      filesystem=\"${filesystem}\",\n      component=\"client_fs\",\n      histogram=\"ExecutionTime\",\n      request=\"WriteData\",\n      units=\"\",\n      instance=~\"$client\",\n    })\n  )\n) or \nhistogram_quantiles(\"q\", 0.5, 0.9, 0.95, 0.99,\n  sum by (le) (\n    increase(ExecutionTime_bucket{\n      filesystem=\"${filesystem}\",\n      component=\"client_fs\",\n      histogram=\"ExecutionTime\",\n      request=\"WriteData\",\n      units=\"usec\",\n      instance=~\"$client\",\n    })\n  )\n) / 1000",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "WriteData Throttler Delay Quantiles (ms)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantiles(\"q\", 0.5, 0.9, 0.95, 0.99,\n  sum by (le) (\n    increase(ThrottlerDelay_bucket{\n      filesystem=\"${filesystem}\",\n      component=\"client_fs\",\n      histogram=\"ThrottlerDelay\",\n      request=\"WriteData\",\n      units=\"\",\n      instance=~\"$client\",\n    })\n  )\n) or \nhistogram_quantiles(\"q\", 0.5, 0.9, 0.95, 0.99,\n  sum by (le) (\n    increase(ThrottlerDelay_bucket{\n      filesystem=\"${filesystem}\",\n      component=\"client_fs\",\n      histogram=\"ThrottlerDelay\",\n      request=\"WriteData\",\n      units=\"usec\",\n      instance=~\"$client\",\n    })\n  )\n) / 1000",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "WriteData Size Histogram",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 26 },
   "targets": [
    {
     "expr": "round(\n  sum by (le) (\n    rate(Size_bucket{\n      filesystem=\"${filesystem}\",\n      component=\"client_fs\",\n      histogram=\"Size\",\n      request=\"WriteData\",\n      instance=~\"$client\",\n    })\n  ), 1\n)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Read Latency Quantiles (ms)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantiles(\"q\", 0.5, 0.9, 0.95, 0.99,\n  sum by (le) (\n    increase(Time_bucket{\n      filesystem=\"${filesystem}\",\n      component=\"client_fs\",\n      histogram=\"Time\",\n      request=\"ReadData\",\n      units=\"\",\n      instance=~\"$client\",\n    })\n  )\n) or \nhistogram_quantiles(\"q\", 0.5, 0.9, 0.95, 0.99,\n  sum by (le) (\n    increase(Time_bucket{\n      filesystem=\"${filesystem}\",\n      component=\"client_fs\",\n      histogram=\"Time\",\n      request=\"ReadData\",\n      units=\"usec\",\n      instance=~\"$client\",\n    })\n  )\n) / 1000",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "ReadData Execution Latency Quantiles (ms)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantiles(\"q\", 0.5, 0.9, 0.95, 0.99,\n  sum by (le) (\n    increase(ExecutionTime_bucket{\n      filesystem=\"${filesystem}\",\n      component=\"client_fs\",\n      histogram=\"ExecutionTime\",\n      request=\"ReadData\",\n      units=\"\",\n      instance=~\"$client\",\n    })\n  )\n) or\nhistogram_quantiles(\"q\", 0.5, 0.9, 0.95, 0.99,\n  sum by (le) (\n    increase(ExecutionTime_bucket{\n      filesystem=\"${filesystem}\",\n      component=\"client_fs\",\n      histogram=\"ExecutionTime\",\n      request=\"ReadData\",\n      units=\"usec\",\n      instance=~\"$client\",\n    })\n  )\n) / 1000",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "ReadData Throttler Delay Quantiles (ms)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantiles(\"q\", 0.5, 0.9, 0.95, 0.99,\n  sum by (le) (\n    increase(ThrottlerDelay_bucket{\n      filesystem=\"${filesystem}\",\n      component=\"client_fs\",\n      histogram=\"ThrottlerDelay\",\n      request=\"ReadData\",\n      units=\"\",\n      instance=~\"$client\",\n    })\n  )\n) or \nhistogram_quantiles(\"q\", 0.5, 0.9, 0.95, 0.99,\n  sum by (le) (\n    increase(ThrottlerDelay_bucket{\n      filesystem=\"${filesystem}\",\n      component=\"client_fs\",\n      histogram=\"ThrottlerDelay\",\n      request=\"ReadData\",\n      units=\"usec\",\n      instance=~\"$client\",\n    })\n  )\n) / 1000",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "ReadData Size Histogram",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 35 },
   "targets": [
    {
     "expr": "round(\n  sum by (le) (\n    rate(Size_bucket{\n      filesystem=\"${filesystem}\",\n      component=\"client_fs\",\n      histogram=\"Size\",\n      request=\"ReadData\",\n      instance=~\"$client\",\n    })\n  ), 1\n)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Control Latency Quantiles (ms)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantiles(\"q\", 0.5, 0.9, 0.95, 0.99,\n  sum by (le) (\n    increase(Time_bucket{\n      filesystem=\"${filesystem}\",\n      component=\"client_fs\",\n      histogram=\"Time\",\n      request!~\"ReadData|WriteData\",\n      units=\"\",\n      instance=~\"$client\",\n    })\n  )\n) or \nhistogram_quantiles(\"q\", 0.5, 0.9, 0.95, 0.99,\n  sum by (le) (\n    increase(Time_bucket{\n      filesystem=\"${filesystem}\",\n      component=\"client_fs\",\n      histogram=\"Time\",\n      request!~\"ReadData|WriteData\",\n      units=\"usec\",\n      instance=~\"$client\",\n    })\n  )\n) / 1000",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "Control Execution Latency Quantiles (ms)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantiles(\"q\", 0.5, 0.9, 0.95, 0.99,\n  sum by (le) (\n    increase(ExecutionTime_bucket{\n      filesystem=\"${filesystem}\",\n      component=\"client_fs\",\n      histogram=\"ExecutionTime\",\n      request!~\"ReadData|WriteData\",\n      instance=~\"$client\",\n    })\n  )\n)",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "Control Throttler Delay Quantiles (ms)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantiles(\"q\", 0.5, 0.9, 0.95, 0.99,\n  sum by (le) (\n    increase(ThrottlerDelay_bucket{\n      filesystem=\"${filesystem}\",\n      component=\"client_fs\",\n      histogram=\"ThrottlerDelay\",\n      request!~\"ReadData|WriteData\",\n      instance=~\"$client\",\n    })\n  )\n)",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "Control Size Histogram",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "round(\n  sum by (le) (\n    increase(Size_bucket{\n      filesystem=\"${filesystem}\",\n      component=\"client_fs\",\n      histogram=\"Size\",\n      request!~\"ReadData|WriteData\",\n      instance=~\"$client\",\n    })\n  ), 1\n)",
     "legendFormat": "{{le}}KB"
    }
   ]
  },
  {
   "title": "Read/Write average time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "sum(\n  rate(\n    {\n      filesystem=\"${filesystem}\",\n      component=\"client_fs\",\n      __name__=\"Time\",\n      request=~\"(ReadData|WriteData)\",\n      instance=~\"$client\",\n    }\n  )\n) by(request)\n  / on(request)\nsum(\n  rate(\n    {\n      filesystem=\"${filesystem}\",\n      component=\"client_fs\",\n      __name__=~\"(Count|Errors)\",\n      request=~\"(ReadData|WriteData)\",\n      instance=~\"$client\",\n    }\n  )\n) by(request)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Read/Write MaxTime",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "max(\n    {\n      filesystem=\"${filesystem}\",\n      component=\"client_fs\",\n      __name__=\"MaxTime\",\n      request=\"ReadData\",\n      instance=~\"$client\",\n    }\n  )",
     "legendFormat": "ReadData"
    },
    {
     "expr": "max(\n    {\n      filesystem=\"${filesystem}\",\n      component=\"client_fs\",\n      __name__=\"MaxTime\",\n      request=\"WriteData\",\n      instance=~\"$client\",\n    }\n  )",
     "legendFormat": "WriteData"
    }
   ]
  },
  {
   "title": "Read/Write TotalErrors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(request)(\n    increase(Errors{\n      filesystem=\"${filesystem}\",\n      component=\"client_fs\",\n      request=~\"ReadData|WriteData\",\n      instance=~\"$client\",\n    }) keep_metric_names\n)",
     "legendFormat": "{{request}}"
    }
   ]
  },
  {
   "title": "Read/Write Errors By Type",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(__name__, request)(\n    increase({\n      filesystem=\"${filesystem}\",\n      component=\"client_fs\",\n      __name__=~\"Errors_.*\",\n      request=~\"ReadData|WriteData\",\n      instance=~\"$client\",\n    }) keep_metric_names\n)",
     "legendFormat": "{{__name__}} {{request}}"
    }
   ]
  },
  {
   "title": "Control Requests average time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "WITH (\n  commonFilters={\n      filesystem=\"${filesystem}\",\n    component=\"client_fs\",\n    instance=~\"$client\",\n  }\n)\nsum by (request)(rate(Time{commonFilters}))\n/\nsum by (request)(rate({commonFilters, __name__=~\"(Count|Errors)\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Control Requests MaxTime",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "max(\n  label_replace(\n    {\n      filesystem=\"${filesystem}\",\n      component=\"client_fs\",\n      __name__=\"MaxTime\",\n      instance=~\"$client\",\n    }, \"request\", \"$1\", \"request\", \"(.*)\"\n  )\n) by (request)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Control TotalErrors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 62 },
   "targets": [
    {
     "expr": "sum by(request)(\n    increase(Errors{\n      filesystem=\"${filesystem}\",\n      component=\"client_fs\",\n      request!~\"ReadData|WriteData\",\n      instance=~\"$client\",\n    }) keep_metric_names\n)",
     "legendFormat": "{{request}}"
    }
   ]
  },
  {
   "title": "Control Errors By Type",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 62 },
   "targets": [
    {
     "expr": "sum by(__name__, request)(\n    increase({\n      filesystem=\"${filesystem}\",\n      component=\"client_fs\",\n      __name__=~\"Errors_.*\",\n      request!~\"ReadData|WriteData\",\n      instance=~\"$client\",\n    }) keep_metric_names\n)",
     "legendFormat": "{{__name__}}, {{request}}"
    }
   ]
  },
  {
   "title": "Storage (NFS-Server - Actor System)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 }
  },
  {
   "title": "Used Bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "TotalBytesCount{filesystem=\"${filesystem}\",  component=\"storage_fs\"}",
     "legendFormat": "TotalBytesCount"
    },
    {
     "expr": "AggregateUsedBytesCount{filesystem=\"${filesystem}\",  component=\"storage_fs\"}",
     "legendFormat": "UsedBytesCount"
    }
   ]
  },
  {
   "title": "Bandwidth Limits",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (__name__) ({filesystem=\"${filesystem}\",  component=\"storage_fs\", __name__=~\"Max.*Bandwidth\"})",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "IOPS Limits",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum by (__name__) ({filesystem=\"${filesystem}\",  component=\"storage_fs\", __name__=~\"Max.*Iops\"})",
     "legendFormat": "{{request}}"
    }
   ]
  },
  {
   "title": "Sessions Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 72 },
   "targets": [
    {
     "expr": "{filesystem=\"${filesystem}\",  component=\"storage_fs\", __name__=~\".*SessionsCount\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Locks Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(UsedLocksCount{filesystem=~\"${filesystem}.*\",  component=\"storage_fs\"})",
     "legendFormat": "UsedLocksCount"
    }
   ]
  },
  {
   "title": "Nodes Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "TotalNodesCount{filesystem=\"${filesystem}\",  component=\"storage_fs\"}",
     "legendFormat": "TotalNodesCount"
    },
    {
     "expr": "AggregateUsedNodesCount{filesystem=\"${filesystem}\",  component=\"storage_fs\"}",
     "legendFormat": "UsedNodesCount "
    }
   ]
  },
  {
   "title": "UsedQuota",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(max(UsedQuota{filesystem=\"${filesystem}\",  component=\"storage_fs\"}))",
     "legendFormat": "UsedQuota"
    },
    {
     "expr": "max(MaxUsedQuota{filesystem=\"${filesystem}\",  component=\"storage_fs\"})",
     "legendFormat": "MaxUsedQuota"
    }
   ]
  },
  {
   "title": "ReadAheadCache",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum(rate(\n  ReadAheadCacheHitCount{\n    filesystem=~\"^${filesystem}.*\",\n    component=\"storage_fs\"\n  }\n))",
     "legendFormat": "HitCount"
    },
    {
     "expr": "sum(ReadAheadCacheNodeCount{\n  filesystem=~\"${filesystem}.*\",\n  component=\"storage_fs\"\n})",
     "legendFormat": "NodeCount"
    }
   ]
  },
  {
   "title": "Requests in Throttler",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(sum by (__name__) ({filesystem=\"${filesystem}\",  component=\"storage_fs\", __name__=~\"(RejectedRequests|PostponedRequests)\"}) ) keep_metric_names ",
     "legendFormat": "{{request}}"
    }
   ]
  },
  {
   "title": "NodeIndexCache",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum(rate(\n  NodeIndexCacheHitCount{\n    filesystem=~\"^${filesystem}.*\",\n    component=\"storage_fs\"\n  }\n))",
     "legendFormat": "HitCount"
    },
    {
     "expr": "sum(NodeIndexCacheNodeCount{\n  filesystem=~\"${filesystem}.*\",\n  component=\"storage_fs\"\n})",
     "legendFormat": "NodeCount"
    }
   ]
  },
  {
   "title": "Handles Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum({filesystem=~\"${filesystem}.*\",  component=\"storage_fs\", __name__=~\"UsedHandlesCount\"})",
     "legendFormat": "UsedHandlesCount"
    }
   ]
  },
  {
   "title": "InMemoryIndexCache Hit",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum by(__name__)(rate(\n  {\n    filesystem=~\"^${filesystem}.*\",\n    component=\"storage_fs\",\n    __name__=~\"InMemoryIndexStateROCacheHitCount|InMemoryIndexStateROCacheMissCount|InMemoryIndexStateRWCount\"\n  } \n)keep_metric_names)",
     "legendFormat": "{{__name__}}"
    }
   ]
  }
 ]
}