{
 "title": "Nebius Shared Filesystem",
 "description": "Dashboard provides an overview of the Nebius Shared Filesystems.",
 "tags": [
  "Nebius",
  "NBS"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "filestore", "query": "label_values(filestore)" }
  ]
 },
 "panels": [
  {
   "title": "FS read latency (quantiles)",
   "type": "timeseries",
   "description": "Percentiles of the filesystem write requests latency. Measured in milliseconds.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(filestore_read_latency_bucket{filestore=\"$filestore\"}[$__rate_interval])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le) (rate(filestore_read_latency_bucket{filestore=\"$filestore\"}[$__rate_interval])))",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.90, sum by(le) (rate(filestore_read_latency_bucket{filestore=\"$filestore\"}[$__rate_interval])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(filestore_read_latency_bucket{filestore=\"$filestore\"}[$__rate_interval])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(filestore_read_latency_bucket{filestore=\"$filestore\"}[$__rate_interval])))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "FS write latency (quantiles)",
   "type": "timeseries",
   "description": "Percentiles of the filesystem read requests latency. Measured in milliseconds.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.1, sum by(le) (rate(filestore_write_latency_bucket{filestore=\"$filestore\"}[$__rate_interval])))",
     "legendFormat": "p10"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(filestore_write_latency_bucket{filestore=\"$filestore\"}[$__rate_interval])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le) (rate(filestore_write_latency_bucket{filestore=\"$filestore\"}[$__rate_interval])))",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.90, sum by(le) (rate(filestore_write_latency_bucket{filestore=\"$filestore\"}[$__rate_interval])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(filestore_write_latency_bucket{filestore=\"$filestore\"}[$__rate_interval])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(filestore_write_latency_bucket{filestore=\"$filestore\"}[$__rate_interval])))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "FS read operations",
   "type": "timeseries",
   "description": "Average read IOPS. Measured in operations per second.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum(rate(filestore_read_ops{filestore=\"$filestore\"}[$__rate_interval]))",
     "legendFormat": "Read"
    },
    {
     "expr": "sum(filestore_read_ops_burst{filestore=\"$filestore\"})",
     "legendFormat": "Read Burst"
    }
   ]
  },
  {
   "title": "FS write operations",
   "type": "timeseries",
   "description": "Average write IOPS. Measured in operations per second.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum(rate(filestore_write_ops{filestore=\"$filestore\"}[$__rate_interval]))",
     "legendFormat": "Write"
    },
    {
     "expr": "sum(filestore_write_ops_burst{filestore=\"$filestore\"})",
     "legendFormat": "Write Burst"
    }
   ]
  },
  {
   "title": "FS read bytes",
   "type": "timeseries",
   "description": "Average read throughput. Measured in bytes per second.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(filestore_read_bytes{filestore=\"$filestore\"}[$__rate_interval]))",
     "legendFormat": "Read"
    },
    {
     "expr": "sum(filestore_read_bytes_burst{filestore=\"$filestore\"})",
     "legendFormat": "Read Burst"
    }
   ]
  },
  {
   "title": "FS write bytes",
   "type": "timeseries",
   "description": "Average write throughput. Measured in bytes per second.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(filestore_write_bytes{filestore=\"$filestore\"}[$__rate_interval]))",
     "legendFormat": "Write"
    },
    {
     "expr": "sum(filestore_write_bytes_burst{filestore=\"$filestore\"})",
     "legendFormat": "Write Burst"
    }
   ]
  },
  {
   "title": "FS read errors",
   "type": "timeseries",
   "description": "Number of times a filesystem fails to read data.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sum(rate(filestore_read_errors{filestore=\"$filestore\"}[$__rate_interval]))",
     "legendFormat": "Read"
    }
   ]
  },
  {
   "title": "FS write errors",
   "type": "timeseries",
   "description": "Number of times a filesystem fails to write data.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "sum(rate(filestore_write_errors{filestore=\"$filestore\"}[$__rate_interval]))",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "FS index operations",
   "type": "timeseries",
   "description": "Number of indexing actions (reads, writes, updates and deletions) performed in a time period.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "sum(rate(filestore_index_ops{filestore=\"$filestore\"}[$__rate_interval]))",
     "legendFormat": "Ops"
    }
   ]
  },
  {
   "title": "FS index errors",
   "type": "timeseries",
   "description": "Number of failed indexing operations in a time period.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "expr": "sum(rate(filestore_index_errors{filestore=\"$filestore\"}[$__rate_interval]))",
     "legendFormat": "Errors"
    }
   ]
  }
 ]
}